# Generated by Django 3.2.7 on 2021-09-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210907_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='email',
            field=models.EmailField(max_length=70, null=True, unique=True),
        ),
    ]
