# Generated by Django 3.2.7 on 2021-09-08 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_category', models.CharField(max_length=255)),
                ('scheme_type', models.CharField(max_length=255)),
                ('scheme_sub_type', models.CharField(max_length=255)),
                ('fund_code', models.CharField(max_length=255, unique=True)),
                ('fund_name', models.CharField(max_length=255)),
                ('fund_option', models.CharField(max_length=255)),
                ('fund_type', models.CharField(max_length=255)),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundsapi.amc')),
            ],
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav', models.FloatField()),
                ('date', models.DateField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundsapi.scheme')),
            ],
            options={
                'unique_together': {('scheme', 'date')},
            },
        ),
    ]
