# Generated by Django 3.2.7 on 2021-09-08 10:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fundsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 9, 8, 10, 33, 31, 571204, tzinfo=utc)),
        ),
    ]
