# Generated by Django 3.2.7 on 2021-09-08 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fundsapi', '0002_alter_nav_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 9, 8, 10, 34, 27, 914285, tzinfo=utc)),
        ),
    ]
