# Generated by Django 3.2.7 on 2021-09-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundsapi', '0003_alter_nav_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
